name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - !!import/single cache-step.yaml

    - name: Install NPM dependencies
      run: npm install